default: &default
  adapter: postgresql
  encoding: unicode
  user: "postgres"
  password: ""
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: atuacao_dev

production:
  <<: *default
  database: atuacao

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
